steps:
  # Backend: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:latest",
        ".",
      ]
    dir: "backend"
    id: "build-backend"

  # Backend: Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend",
      ]
    id: "push-backend"
    waitFor: ["build-backend"]

  # Deploy Backend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_BACKEND_SERVICE_NAME}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--service-account=${_CLOUD_RUN_SA}",
        "--memory=4Gi",
        "--cpu=2",
        "--max-instances=10",
        "--min-instances=0",
      ]
    id: "deploy-backend"
    waitFor: ["push-backend"]

  # Get Backend URL for Frontend build
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        BACKEND_URL=$$(gcloud run services describe ${_BACKEND_SERVICE_NAME} --region=${_REGION} --format="value(status.url)")
        echo "BACKEND_URL=$$BACKEND_URL" > /workspace/backend_url.env
    id: "get-backend-url"
    waitFor: ["deploy-backend"]

  # Frontend: Build Docker image with dynamic Backend URL
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        source /workspace/backend_url.env
        docker build \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA} \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest \
          --build-arg VITE_BACKEND_BASE_URL=$$BACKEND_URL \
          .
    dir: "frontend"
    id: "build-frontend"
    waitFor: ["get-backend-url"]

  # Frontend: Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend",
      ]
    id: "push-frontend"
    waitFor: ["build-frontend"]

  # Deploy Frontend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_FRONTEND_SERVICE_NAME}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA}",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--service-account=${_CLOUD_RUN_SA}",
        "--memory=2Gi",
        "--cpu=1",
        "--max-instances=5",
        "--min-instances=0",
      ]
    id: "deploy-frontend"
    waitFor: ["push-frontend"]

# Substitutions are managed by Terraform in Cloud Build Trigger

# Images to be stored
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA}"

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
