steps:
  # Build base image with Python + TeX Live Full
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "backend/Dockerfile.base",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend-base:latest",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend-base:${BUILD_ID}",
        ".",
      ]
    id: "build-base-image"

  # Push base image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend-base",
      ]
    id: "push-base-image"
    waitFor: ["build-base-image"]

# Images to be stored
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend-base:latest"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend-base:${BUILD_ID}"

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8" # High CPU for faster TeX Live installation

timeout: 1800s # 30 minutes timeout for TeX Live installation
