steps:
  # Backend: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:latest",
        ".",
      ]
    dir: "backend"
    id: "build-backend"

  # Backend: Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend",
      ]
    id: "push-backend"
    waitFor: ["build-backend"]

  # Frontend: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:latest",
        "--build-arg",
        "VITE_BACKEND_BASE_URL=https://${_BACKEND_SERVICE_NAME}-${_BACKEND_SERVICE_HASH}-${_REGION}.a.run.app",
        ".",
      ]
    dir: "frontend"
    id: "build-frontend"
    waitFor: ["deploy-backend"] # バックエンドデプロイ後にフロントエンドをビルド

  # Frontend: Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "--all-tags",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend",
      ]
    id: "push-frontend"
    waitFor: ["build-frontend"]

  # Deploy Backend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_BACKEND_SERVICE_NAME}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--service-account=${_CLOUD_RUN_SA}",
        "--memory=4Gi",
        "--cpu=2",
        "--max-instances=10",
        "--min-instances=0",
      ]
    id: "deploy-backend"
    waitFor: ["push-backend"]

  # Deploy Frontend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_FRONTEND_SERVICE_NAME}",
        "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA}",
        "--region=${_REGION}",
        "--platform=managed",
        "--allow-unauthenticated",
        "--memory=2Gi",
        "--cpu=1",
        "--max-instances=5",
        "--min-instances=0",
      ]
    id: "deploy-frontend"
    waitFor: ["push-frontend"]

# Substitutions (variables)
substitutions:
  _REGION: "asia-northeast1"
  _REPOSITORY: "jaxiv-images"
  _BACKEND_SERVICE_NAME: "jaxiv-backend"
  _FRONTEND_SERVICE_NAME: "jaxiv-frontend"
  _BACKEND_SERVICE_HASH: "uc" # This will be updated after first deployment
  _CLOUD_RUN_SA: "jaxiv-cloud-run@jaxiv-465416.iam.gserviceaccount.com"

# Images to be stored
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/backend:${COMMIT_SHA}"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${COMMIT_SHA}"

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
