services:
  - name: arxiv-translation-service
    type: web
    plan: free
    runtime: docker
    repo: https://github.com/Higashi-Masafumi/jaXiv
    dockerfilePath: Dockerfile.render
    rootDir: ./backend
  - name: jaxiv-frontend
    type: web
    plan: free
    runtime: docker
    repo: https://github.com/Higashi-Masafumi/jaXiv
    dockerfilePath: Dockerfile
    rootDir: ./frontend
    envVars:
      - key: API_BASE_URL
        value: https://arxiv-translation-service.onrender.com
