import uuid
from abc import ABC, abstractmethod
from datetime import datetime

from pydantic import BaseModel, ConfigDict

from domain.entities.blog import BlogPost
from domain.value_objects.blog_source_type import BlogSourceType
from domain.value_objects.user_id import UserId


class AccessiblePaper(BaseModel):
	"""Lightweight read model for a paper the requester may access."""

	model_config = ConfigDict(frozen=True)

	title: str
	source_type: BlogSourceType


class IBlogPostRepository(ABC):
	"""Repository for persisting and retrieving blog posts."""

	@abstractmethod
	async def find_by_paper_id(self, paper_id: str) -> BlogPost | None:
		"""Find a blog post by paper ID."""
		...

	@abstractmethod
	async def find_accessible_papers_by_paper_ids(
		self, paper_ids: list[str], user_id: UserId
	) -> dict[str, AccessiblePaper]:
		"""Return paper_id -> accessible paper info for papers the user may access.

		A paper is accessible when it is a public arXiv post, or a PDF post owned
		by ``user_id``. Inaccessible papers (e.g. other users' private PDFs) and
		unknown paper IDs are omitted from the result.
		"""
		...

	@abstractmethod
	async def find_all(
		self, page: int, page_size: int, keyword: str | None = None
	) -> list[BlogPost]:
		"""Find arXiv blog posts ordered by created_at descending with pagination.

		When ``keyword`` is given, results are filtered by a case-insensitive partial
		match against the title, summary, or authors.
		"""
		...

	@abstractmethod
	async def count_all(self, keyword: str | None = None) -> int:
		"""Return the total number of arXiv blog posts.

		When ``keyword`` is given, only posts matching it (title/summary/authors) are
		counted.
		"""
		...

	@abstractmethod
	async def find_all_by_user(self, user_id: UserId, page: int, page_size: int) -> list[BlogPost]:
		"""Find a user's PDF blog posts ordered by created_at descending with pagination."""
		...

	@abstractmethod
	async def count_all_by_user(self, user_id: UserId) -> int:
		"""Return the total number of PDF blog posts for a given user."""
		...

	@abstractmethod
	async def count_generated_by_user(self, user_id: UserId, since: datetime | None = None) -> int:
		"""Count blog posts generated by a user (all sources, optionally since a given datetime)."""
		...

	@abstractmethod
	async def find_matching_arxiv(
		self, keywords: list[str], exclude_ids: set[uuid.UUID], limit: int
	) -> list[BlogPost]:
		"""Return public arXiv posts whose title or summary matches any keyword.

		Posts whose id is in ``exclude_ids`` are omitted; results are ordered by
		``created_at`` descending and limited to ``limit``.
		"""
		...

	@abstractmethod
	async def save(self, blog_post: BlogPost) -> BlogPost:
		"""Save a blog post and return the persisted entity."""
		...
