"""fix_datetime_timezone

Revision ID: 265bdba59a02
Revises: ec4cf5023ae7
Create Date: 2026-03-27 23:29:19.343004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265bdba59a02'
down_revision: Union[str, Sequence[str], None] = 'ec4cf5023ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'arxivpapermetadatawithtranslatedurlmodel',
		'published_date',
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		nullable=True,
	)
	op.alter_column(
		'blogpostcontentmodel',
		'created_at',
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		nullable=True,
	)
	op.alter_column(
		'blogpostcontentmodel',
		'updated_at',
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		nullable=True,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'blogpostcontentmodel',
		'updated_at',
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		nullable=False,
	)
	op.alter_column(
		'blogpostcontentmodel',
		'created_at',
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		nullable=False,
	)
	op.alter_column(
		'arxivpapermetadatawithtranslatedurlmodel',
		'published_date',
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		nullable=False,
	)
	# ### end Alembic commands ###
