"""add_chat_thread_table

Revision ID: 653ef8c5d274
Revises: 61c449449d0d
Create Date: 2026-04-26 21:48:31.379454

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '653ef8c5d274'
down_revision: Union[str, Sequence[str], None] = '61c449449d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'chat_thread',
		'created_at',
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=True,
	)
	op.alter_column(
		'chat_thread',
		'updated_at',
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=True,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		'chat_thread',
		'updated_at',
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=False,
	)
	op.alter_column(
		'chat_thread',
		'created_at',
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=False,
	)
	# ### end Alembic commands ###
