"""add_metadata_to_blog_table

Revision ID: 91c1b44c9807
Revises: 265bdba59a02
Create Date: 2026-03-29 03:33:47.566054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c1b44c9807'
down_revision: Union[str, Sequence[str], None] = '265bdba59a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		'blogpostcontentmodel', sa.Column('title', sa.Text(), server_default='', nullable=False)
	)
	op.add_column(
		'blogpostcontentmodel', sa.Column('summary', sa.Text(), server_default='', nullable=False)
	)
	op.add_column(
		'blogpostcontentmodel',
		sa.Column('authors', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
	)
	op.add_column('blogpostcontentmodel', sa.Column('source_url', sa.Text(), nullable=True))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('blogpostcontentmodel', 'source_url')
	op.drop_column('blogpostcontentmodel', 'authors')
	op.drop_column('blogpostcontentmodel', 'summary')
	op.drop_column('blogpostcontentmodel', 'title')
	# ### end Alembic commands ###
