"""create arxiv table

Revision ID: a60fa4275e25
Revises:
Create Date: 2025-07-09 00:12:45.811617

"""

from collections.abc import Sequence

import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a60fa4275e25'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'arxivpapermetadatawithtranslatedurlmodel',
		sqlmodel.Column('id', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('paper_id', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('title', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('summary', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('published_date', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('authors', sqlmodel.AutoString(), nullable=True),
		sqlmodel.Column('source_url', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('translated_file_storage_path', sqlmodel.AutoString(), nullable=False),
		sqlmodel.Column('translated_url', sqlmodel.AutoString(), nullable=False),
		sqlmodel.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		op.f('ix_arxivpapermetadatawithtranslatedurlmodel_paper_id'),
		'arxivpapermetadatawithtranslatedurlmodel',
		['paper_id'],
		unique=True,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(
		op.f('ix_arxivpapermetadatawithtranslatedurlmodel_paper_id'),
		table_name='arxivpapermetadatawithtranslatedurlmodel',
	)
	op.drop_table('arxivpapermetadatawithtranslatedurlmodel')
	# ### end Alembic commands ###
