"""add_araxiv_tables

Revision ID: ec4cf5023ae7
Revises:
Create Date: 2026-03-27 23:17:59.931778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec4cf5023ae7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'arxivpapermetadatawithtranslatedurlmodel',
		sa.Column('id', sa.Uuid(), nullable=False),
		sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column('published_date', sa.DateTime(), nullable=False),
		sa.Column('authors', sa.ARRAY(sa.String()), nullable=True),
		sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column(
			'translated_file_storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False
		),
		sa.Column('translated_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		op.f('ix_arxivpapermetadatawithtranslatedurlmodel_paper_id'),
		'arxivpapermetadatawithtranslatedurlmodel',
		['paper_id'],
		unique=True,
	)
	op.create_table(
		'blogpostcontentmodel',
		sa.Column('id', sa.Uuid(), nullable=False),
		sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column('content', sa.Text(), nullable=True),
		sa.Column('created_at', sa.DateTime(), nullable=False),
		sa.Column('updated_at', sa.DateTime(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(
		op.f('ix_blogpostcontentmodel_paper_id'), 'blogpostcontentmodel', ['paper_id'], unique=True
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_blogpostcontentmodel_paper_id'), table_name='blogpostcontentmodel')
	op.drop_table('blogpostcontentmodel')
	op.drop_index(
		op.f('ix_arxivpapermetadatawithtranslatedurlmodel_paper_id'),
		table_name='arxivpapermetadatawithtranslatedurlmodel',
	)
	op.drop_table('arxivpapermetadatawithtranslatedurlmodel')
	# ### end Alembic commands ###
