"""add_chat_thread

Revision ID: f8754dbb89e2
Revises: 61c449449d0d
Create Date: 2026-04-27 00:37:07.208341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f8754dbb89e2'
down_revision: Union[str, Sequence[str], None] = '61c449449d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'chat_thread',
		sa.Column('id', sa.Uuid(), nullable=False),
		sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
		sa.Column('user_id', sa.UUID(), nullable=False),
		sa.Column(
			'messages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False
		),
		sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
		sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_index(op.f('ix_chat_thread_paper_id'), 'chat_thread', ['paper_id'], unique=False)
	op.create_index(op.f('ix_chat_thread_user_id'), 'chat_thread', ['user_id'], unique=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_chat_thread_user_id'), table_name='chat_thread')
	op.drop_index(op.f('ix_chat_thread_paper_id'), table_name='chat_thread')
	op.drop_table('chat_thread')
	# ### end Alembic commands ###
