// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client'
import { client } from './client.gen'
import type {
  GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
  GenerateBlogFromPdfApiV1BlogPdfPostData,
  GenerateBlogFromPdfApiV1BlogPdfPostErrors,
  GenerateBlogFromPdfApiV1BlogPdfPostResponses,
  GetBlogApiV1BlogPaperIdGetData,
  GetBlogApiV1BlogPaperIdGetErrors,
  GetBlogApiV1BlogPaperIdGetResponses,
  ListBlogsApiV1BlogGetData,
  ListBlogsApiV1BlogGetResponses,
  RootGetData,
  RootGetResponses,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
  TriggerErrorSentryDebugGetData,
  TriggerErrorSentryDebugGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * List Blogs
 */
export const listBlogsApiV1BlogGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListBlogsApiV1BlogGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListBlogsApiV1BlogGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/v1/blog/', ...options })

/**
 * Translate Sync
 */
export const translateSyncApiV1TranslateArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}', ...options })

/**
 * Translate Stream
 */
export const translateStreamApiV1TranslateArxivArxivPaperIdStreamGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}/stream', ...options })

/**
 * Generate Blog
 */
export const generateBlogApiV1BlogArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
    GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({ url: '/api/v1/blog/arxiv/{arxiv_paper_id}', ...options })

/**
 * Get Blog
 */
export const getBlogApiV1BlogPaperIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBlogApiV1BlogPaperIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBlogApiV1BlogPaperIdGetResponses,
    GetBlogApiV1BlogPaperIdGetErrors,
    ThrowOnError
  >({ url: '/api/v1/blog/{paper_id}', ...options })

/**
 * Generate Blog From Pdf
 */
export const generateBlogFromPdfApiV1BlogPdfPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GenerateBlogFromPdfApiV1BlogPdfPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateBlogFromPdfApiV1BlogPdfPostResponses,
    GenerateBlogFromPdfApiV1BlogPdfPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: '/api/v1/blog/pdf',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })

/**
 * Trigger Error
 */
export const triggerErrorSentryDebugGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TriggerErrorSentryDebugGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TriggerErrorSentryDebugGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/sentry-debug', ...options })
