// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
  GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
  GetBlogApiV1BlogArxivArxivPaperIdGetData,
  GetBlogApiV1BlogArxivArxivPaperIdGetErrors,
  GetBlogApiV1BlogArxivArxivPaperIdGetResponses,
  RootGetData,
  RootGetResponses,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
  TriggerErrorSentryDebugGetData,
  TriggerErrorSentryDebugGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Translate Sync
 */
export const translateSyncApiV1TranslateArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}', ...options })

/**
 * Translate Stream
 */
export const translateStreamApiV1TranslateArxivArxivPaperIdStreamGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}/stream', ...options })

/**
 * Get Blog
 */
export const getBlogApiV1BlogArxivArxivPaperIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBlogApiV1BlogArxivArxivPaperIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBlogApiV1BlogArxivArxivPaperIdGetResponses,
    GetBlogApiV1BlogArxivArxivPaperIdGetErrors,
    ThrowOnError
  >({ url: '/api/v1/blog/arxiv/{arxiv_paper_id}', ...options })

/**
 * Generate Blog
 */
export const generateBlogApiV1BlogArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
    GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({ url: '/api/v1/blog/arxiv/{arxiv_paper_id}', ...options })

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })

/**
 * Trigger Error
 */
export const triggerErrorSentryDebugGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TriggerErrorSentryDebugGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TriggerErrorSentryDebugGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/sentry-debug', ...options })
