// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from './client'
import { client } from './client.gen'
import type {
  ChatWithPaperApiV1ChatPaperPaperIdPostData,
  ChatWithPaperApiV1ChatPaperPaperIdPostErrors,
  ChatWithPaperApiV1ChatPaperPaperIdPostResponses,
  CreateCheckoutSessionApiV1BillingCheckoutSessionPostData,
  CreateCheckoutSessionApiV1BillingCheckoutSessionPostErrors,
  CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponses,
  CreatePortalSessionApiV1BillingPortalSessionPostData,
  CreatePortalSessionApiV1BillingPortalSessionPostErrors,
  CreatePortalSessionApiV1BillingPortalSessionPostResponses,
  DeleteChatThreadApiV1ChatThreadsThreadIdDeleteData,
  DeleteChatThreadApiV1ChatThreadsThreadIdDeleteErrors,
  DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponses,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
  GenerateBlogFromPdfApiV1BlogPdfPostData,
  GenerateBlogFromPdfApiV1BlogPdfPostErrors,
  GenerateBlogFromPdfApiV1BlogPdfPostResponses,
  GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostData,
  GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors,
  GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostResponses,
  GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetData,
  GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors,
  GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetResponses,
  GetBlogApiV1BlogPaperIdGetData,
  GetBlogApiV1BlogPaperIdGetErrors,
  GetBlogApiV1BlogPaperIdGetResponses,
  GetChatThreadApiV1ChatThreadsThreadIdGetData,
  GetChatThreadApiV1ChatThreadsThreadIdGetErrors,
  GetChatThreadApiV1ChatThreadsThreadIdGetResponses,
  GetMyChatDailyCountApiV1ChatMyDailyCountGetData,
  GetMyChatDailyCountApiV1ChatMyDailyCountGetResponses,
  GetMyGenerationCountApiV1BlogMyGenerationCountGetData,
  GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses,
  GetMySubscriptionApiV1BillingMeGetData,
  GetMySubscriptionApiV1BillingMeGetResponses,
  ListBlogsApiV1BlogGetData,
  ListBlogsApiV1BlogGetErrors,
  ListBlogsApiV1BlogGetResponses,
  ListChatThreadsApiV1ChatPaperPaperIdThreadsGetData,
  ListChatThreadsApiV1ChatPaperPaperIdThreadsGetErrors,
  ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponses,
  ListMyBlogsApiV1BlogMyGetData,
  ListMyBlogsApiV1BlogMyGetErrors,
  ListMyBlogsApiV1BlogMyGetResponses,
  RagSearchImageApiV1BlogPaperIdRagImagePostData,
  RagSearchImageApiV1BlogPaperIdRagImagePostErrors,
  RagSearchImageApiV1BlogPaperIdRagImagePostResponses,
  RagSearchTextApiV1BlogPaperIdRagTextPostData,
  RagSearchTextApiV1BlogPaperIdRagTextPostErrors,
  RagSearchTextApiV1BlogPaperIdRagTextPostResponses,
  RootGetData,
  RootGetResponses,
  StripeWebhookApiV1BillingWebhookPostData,
  StripeWebhookApiV1BillingWebhookPostErrors,
  StripeWebhookApiV1BillingWebhookPostResponses,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
  TriggerErrorSentryDebugGetData,
  TriggerErrorSentryDebugGetResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Translate Sync
 */
export const translateSyncApiV1TranslateArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses,
    TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}', ...options })

/**
 * Translate Stream
 */
export const translateStreamApiV1TranslateArxivArxivPaperIdStreamGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses,
    TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors,
    ThrowOnError
  >({ url: '/api/v1/translate/arxiv/{arxiv_paper_id}/stream', ...options })

/**
 * List Blogs
 */
export const listBlogsApiV1BlogGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListBlogsApiV1BlogGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListBlogsApiV1BlogGetResponses,
    ListBlogsApiV1BlogGetErrors,
    ThrowOnError
  >({ url: '/api/v1/blog/', ...options })

/**
 * List My Blogs
 */
export const listMyBlogsApiV1BlogMyGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListMyBlogsApiV1BlogMyGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListMyBlogsApiV1BlogMyGetResponses,
    ListMyBlogsApiV1BlogMyGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/my',
    ...options,
  })

/**
 * Get My Generation Count
 */
export const getMyGenerationCountApiV1BlogMyGenerationCountGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetMyGenerationCountApiV1BlogMyGenerationCountGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/my/generation-count',
    ...options,
  })

/**
 * Generate Blog
 */
export const generateBlogApiV1BlogArxivArxivPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses,
    GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/arxiv/{arxiv_paper_id}',
    ...options,
  })

/**
 * Generate Blog Stream
 */
export const generateBlogStreamApiV1BlogArxivArxivPaperIdStreamGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetResponses,
    GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/arxiv/{arxiv_paper_id}/stream',
    ...options,
  })

/**
 * Rag Search Text
 */
export const ragSearchTextApiV1BlogPaperIdRagTextPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RagSearchTextApiV1BlogPaperIdRagTextPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RagSearchTextApiV1BlogPaperIdRagTextPostResponses,
    RagSearchTextApiV1BlogPaperIdRagTextPostErrors,
    ThrowOnError
  >({
    url: '/api/v1/blog/{paper_id}/rag/text',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Rag Search Image
 */
export const ragSearchImageApiV1BlogPaperIdRagImagePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RagSearchImageApiV1BlogPaperIdRagImagePostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    RagSearchImageApiV1BlogPaperIdRagImagePostResponses,
    RagSearchImageApiV1BlogPaperIdRagImagePostErrors,
    ThrowOnError
  >({
    url: '/api/v1/blog/{paper_id}/rag/image',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Get Blog
 */
export const getBlogApiV1BlogPaperIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBlogApiV1BlogPaperIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBlogApiV1BlogPaperIdGetResponses,
    GetBlogApiV1BlogPaperIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/{paper_id}',
    ...options,
  })

/**
 * Generate Blog From Pdf
 */
export const generateBlogFromPdfApiV1BlogPdfPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GenerateBlogFromPdfApiV1BlogPdfPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GenerateBlogFromPdfApiV1BlogPdfPostResponses,
    GenerateBlogFromPdfApiV1BlogPdfPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/pdf',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Generate Blog From Pdf Stream
 */
export const generateBlogFromPdfStreamApiV1BlogPdfStreamPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).post<
    GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostResponses,
    GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/blog/pdf/stream',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  })

/**
 * Chat with a paper using Gemini (SSE stream)
 */
export const chatWithPaperApiV1ChatPaperPaperIdPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChatWithPaperApiV1ChatPaperPaperIdPostData, ThrowOnError>,
) =>
  (options.client ?? client).sse.post<
    ChatWithPaperApiV1ChatPaperPaperIdPostResponses,
    ChatWithPaperApiV1ChatPaperPaperIdPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/chat/paper/{paper_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * List chat threads for the current user on a paper
 */
export const listChatThreadsApiV1ChatPaperPaperIdThreadsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListChatThreadsApiV1ChatPaperPaperIdThreadsGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponses,
    ListChatThreadsApiV1ChatPaperPaperIdThreadsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/chat/paper/{paper_id}/threads',
    ...options,
  })

/**
 * Delete a chat thread owned by the current user
 */
export const deleteChatThreadApiV1ChatThreadsThreadIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteChatThreadApiV1ChatThreadsThreadIdDeleteData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).delete<
    DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponses,
    DeleteChatThreadApiV1ChatThreadsThreadIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/chat/threads/{thread_id}',
    ...options,
  })

/**
 * Get full message history for a chat thread
 */
export const getChatThreadApiV1ChatThreadsThreadIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetChatThreadApiV1ChatThreadsThreadIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetChatThreadApiV1ChatThreadsThreadIdGetResponses,
    GetChatThreadApiV1ChatThreadsThreadIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/chat/threads/{thread_id}',
    ...options,
  })

/**
 * Get the current user's chat usage for today
 */
export const getMyChatDailyCountApiV1ChatMyDailyCountGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    GetMyChatDailyCountApiV1ChatMyDailyCountGetData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).get<
    GetMyChatDailyCountApiV1ChatMyDailyCountGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/chat/my/daily-count',
    ...options,
  })

/**
 * Get My Subscription
 */
export const getMySubscriptionApiV1BillingMeGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetMySubscriptionApiV1BillingMeGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMySubscriptionApiV1BillingMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/billing/me',
    ...options,
  })

/**
 * Create Checkout Session
 */
export const createCheckoutSessionApiV1BillingCheckoutSessionPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    CreateCheckoutSessionApiV1BillingCheckoutSessionPostData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponses,
    CreateCheckoutSessionApiV1BillingCheckoutSessionPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/billing/checkout-session',
    ...options,
  })

/**
 * Create Portal Session
 */
export const createPortalSessionApiV1BillingPortalSessionPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    CreatePortalSessionApiV1BillingPortalSessionPostData,
    ThrowOnError
  >,
) =>
  (options?.client ?? client).post<
    CreatePortalSessionApiV1BillingPortalSessionPostResponses,
    CreatePortalSessionApiV1BillingPortalSessionPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/billing/portal-session',
    ...options,
  })

/**
 * Stripe Webhook
 */
export const stripeWebhookApiV1BillingWebhookPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<StripeWebhookApiV1BillingWebhookPostData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    StripeWebhookApiV1BillingWebhookPostResponses,
    StripeWebhookApiV1BillingWebhookPostErrors,
    ThrowOnError
  >({ url: '/api/v1/billing/webhook', ...options })

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(
  options?: Options<RootGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
    url: '/',
    ...options,
  })

/**
 * Trigger Error
 */
export const triggerErrorSentryDebugGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<TriggerErrorSentryDebugGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    TriggerErrorSentryDebugGetResponses,
    unknown,
    ThrowOnError
  >({ url: '/sentry-debug', ...options })
