// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * BlogPostResponseSchema
 */
export type BlogPostResponseSchema = {
  /**
   * Paper Id
   */
  paper_id: string
  /**
   * Title
   */
  title: string
  /**
   * Summary
   */
  summary: string
  /**
   * Authors
   */
  authors: Array<string>
  /**
   * Source Url
   */
  source_url: string | null
  /**
   * Content
   */
  content: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * Body_generate_blog_from_pdf_api_v1_blog_pdf_post
 */
export type BodyGenerateBlogFromPdfApiV1BlogPdfPost = {
  /**
   * File
   *
   * PDF file of the paper
   */
  file: Blob | File
}

/**
 * Body_generate_blog_from_pdf_stream_api_v1_blog_pdf_stream_post
 */
export type BodyGenerateBlogFromPdfStreamApiV1BlogPdfStreamPost = {
  /**
   * File
   *
   * PDF file of the paper
   */
  file: Blob | File
}

/**
 * ChatDailyCountResponse
 */
export type ChatDailyCountResponse = {
  /**
   * Daily
   */
  daily: number
  /**
   * Limit
   */
  limit: number | null
}

/**
 * ChatMessageResponse
 */
export type ChatMessageResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Role
   */
  role: 'user' | 'assistant'
  /**
   * Content
   */
  content: Array<
    | ({
        type: 'text'
      } & TextBlock)
    | ({
        type: 'tool_use'
      } & ToolUseBlock)
    | ({
        type: 'tool_result'
      } & ToolResultBlock)
  >
  /**
   * Timestamp
   */
  timestamp: string
}

/**
 * ChatRequest
 */
export type ChatRequest = {
  /**
   * Message
   *
   * User message text
   */
  message: string
  /**
   * Thread Id
   *
   * Existing thread ID to continue
   */
  thread_id?: string | null
}

/**
 * ChatThreadListResponse
 */
export type ChatThreadListResponse = {
  /**
   * Threads
   */
  threads: Array<ChatThreadSummaryResponse>
}

/**
 * ChatThreadResponse
 */
export type ChatThreadResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Paper Id
   */
  paper_id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Messages
   */
  messages?: Array<ChatMessageResponse>
}

/**
 * ChatThreadSummaryResponse
 */
export type ChatThreadSummaryResponse = {
  /**
   * Id
   */
  id: string
  /**
   * Paper Id
   */
  paper_id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Message Count
   */
  message_count: number
  /**
   * Title
   */
  title: string
}

/**
 * GenerationCountResponseSchema
 */
export type GenerationCountResponseSchema = {
  /**
   * Monthly
   */
  monthly: number
  /**
   * Total
   */
  total: number
  /**
   * Limit
   */
  limit: number | null
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * MySubscriptionResponse
 */
export type MySubscriptionResponse = {
  plan: SubscriptionPlan
  /**
   * Current Period End
   */
  current_period_end: string | null
  /**
   * Cancel At Period End
   */
  cancel_at_period_end: boolean
  /**
   * Has Billing Account
   */
  has_billing_account: boolean
}

/**
 * PaginatedBlogPostResponseSchema
 */
export type PaginatedBlogPostResponseSchema = {
  /**
   * Items
   */
  items: Array<BlogPostResponseSchema>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Page Size
   */
  page_size: number
  /**
   * Total Pages
   */
  total_pages: number
}

/**
 * RagImageItemSchema
 */
export type RagImageItemSchema = {
  /**
   * Image Url
   */
  image_url: string
  /**
   * Caption
   */
  caption: string | null
  /**
   * Page Number
   */
  page_number: number
}

/**
 * RagSearchImageResponseSchema
 */
export type RagSearchImageResponseSchema = {
  /**
   * Items
   */
  items: Array<RagImageItemSchema>
}

/**
 * RagSearchRequestSchema
 */
export type RagSearchRequestSchema = {
  /**
   * Query
   */
  query: string
  /**
   * Limit
   */
  limit?: number
}

/**
 * RagSearchTextResponseSchema
 */
export type RagSearchTextResponseSchema = {
  /**
   * Chunks
   */
  chunks: Array<RagTextChunkSchema>
}

/**
 * RagTextChunkSchema
 */
export type RagTextChunkSchema = {
  /**
   * Text
   */
  text: string
  /**
   * Page Number
   */
  page_number: number
}

/**
 * RedirectUrlResponse
 */
export type RedirectUrlResponse = {
  /**
   * Url
   */
  url: string
}

/**
 * SubscriptionPlan
 */
export type SubscriptionPlan = 'free' | 'paid'

/**
 * TargetLanguage
 *
 * The target language for translation.
 */
export type TargetLanguage = 'japanese'

/**
 * TextBlock
 *
 * Anthropic 互換の text content block。`type` は OpenAPI で required にする
 * ため敢えてデフォルト値を持たせず、コンストラクタで明示的に指定する運用とする。
 */
export type TextBlock = {
  /**
   * Type
   */
  type: 'text'
  /**
   * Text
   */
  text: string
}

/**
 * ToolResultBlock
 */
export type ToolResultBlock = {
  /**
   * Type
   */
  type: 'tool_result'
  /**
   * Tool Use Id
   */
  tool_use_id: string
  /**
   * Name
   */
  name: string
  /**
   * Content
   */
  content: {
    [key: string]: unknown
  }
  /**
   * Is Error
   */
  is_error?: boolean
}

/**
 * ToolUseBlock
 */
export type ToolUseBlock = {
  /**
   * Type
   */
  type: 'tool_use'
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Input
   */
  input?: {
    [key: string]: unknown
  }
}

/**
 * TranslateResponseSchema
 */
export type TranslateResponseSchema = {
  /**
   * Message
   */
  message: string
  /**
   * Translated Pdf Url
   */
  translated_pdf_url: string
  /**
   * Translated Language
   */
  translated_language: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The ID of the paper
     */
    arxiv_paper_id: string
  }
  query: {
    /**
     * The target language
     */
    target_language: TargetLanguage
  }
  url: '/api/v1/translate/arxiv/{arxiv_paper_id}'
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostError =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors]

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: TranslateResponseSchema
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponse =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses]

export type ListBlogsApiV1BlogGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number
  }
  url: '/api/v1/blog/'
}

export type ListBlogsApiV1BlogGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListBlogsApiV1BlogGetError =
  ListBlogsApiV1BlogGetErrors[keyof ListBlogsApiV1BlogGetErrors]

export type ListBlogsApiV1BlogGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedBlogPostResponseSchema
}

export type ListBlogsApiV1BlogGetResponse =
  ListBlogsApiV1BlogGetResponses[keyof ListBlogsApiV1BlogGetResponses]

export type ListMyBlogsApiV1BlogMyGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number
  }
  url: '/api/v1/blog/my'
}

export type ListMyBlogsApiV1BlogMyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListMyBlogsApiV1BlogMyGetError =
  ListMyBlogsApiV1BlogMyGetErrors[keyof ListMyBlogsApiV1BlogMyGetErrors]

export type ListMyBlogsApiV1BlogMyGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedBlogPostResponseSchema
}

export type ListMyBlogsApiV1BlogMyGetResponse =
  ListMyBlogsApiV1BlogMyGetResponses[keyof ListMyBlogsApiV1BlogMyGetResponses]

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/blog/my/generation-count'
}

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses = {
  /**
   * Successful Response
   */
  200: GenerationCountResponseSchema
}

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetResponse =
  GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses[keyof GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses]

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The arXiv paper ID
     */
    arxiv_paper_id: string
  }
  query?: never
  url: '/api/v1/blog/arxiv/{arxiv_paper_id}'
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostError =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors]

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponse =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses]

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The arXiv paper ID
     */
    arxiv_paper_id: string
  }
  query?: never
  url: '/api/v1/blog/arxiv/{arxiv_paper_id}/stream'
}

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetError =
  GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors[keyof GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors]

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostData = {
  body: RagSearchRequestSchema
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}/rag/text'
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostError =
  RagSearchTextApiV1BlogPaperIdRagTextPostErrors[keyof RagSearchTextApiV1BlogPaperIdRagTextPostErrors]

export type RagSearchTextApiV1BlogPaperIdRagTextPostResponses = {
  /**
   * Successful Response
   */
  200: RagSearchTextResponseSchema
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostResponse =
  RagSearchTextApiV1BlogPaperIdRagTextPostResponses[keyof RagSearchTextApiV1BlogPaperIdRagTextPostResponses]

export type RagSearchImageApiV1BlogPaperIdRagImagePostData = {
  body: RagSearchRequestSchema
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}/rag/image'
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostError =
  RagSearchImageApiV1BlogPaperIdRagImagePostErrors[keyof RagSearchImageApiV1BlogPaperIdRagImagePostErrors]

export type RagSearchImageApiV1BlogPaperIdRagImagePostResponses = {
  /**
   * Successful Response
   */
  200: RagSearchImageResponseSchema
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostResponse =
  RagSearchImageApiV1BlogPaperIdRagImagePostResponses[keyof RagSearchImageApiV1BlogPaperIdRagImagePostResponses]

export type GetBlogApiV1BlogPaperIdGetData = {
  body?: never
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}'
}

export type GetBlogApiV1BlogPaperIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetBlogApiV1BlogPaperIdGetError =
  GetBlogApiV1BlogPaperIdGetErrors[keyof GetBlogApiV1BlogPaperIdGetErrors]

export type GetBlogApiV1BlogPaperIdGetResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GetBlogApiV1BlogPaperIdGetResponse =
  GetBlogApiV1BlogPaperIdGetResponses[keyof GetBlogApiV1BlogPaperIdGetResponses]

export type GenerateBlogFromPdfApiV1BlogPdfPostData = {
  body: BodyGenerateBlogFromPdfApiV1BlogPdfPost
  path?: never
  query?: never
  url: '/api/v1/blog/pdf'
}

export type GenerateBlogFromPdfApiV1BlogPdfPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogFromPdfApiV1BlogPdfPostError =
  GenerateBlogFromPdfApiV1BlogPdfPostErrors[keyof GenerateBlogFromPdfApiV1BlogPdfPostErrors]

export type GenerateBlogFromPdfApiV1BlogPdfPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogFromPdfApiV1BlogPdfPostResponse =
  GenerateBlogFromPdfApiV1BlogPdfPostResponses[keyof GenerateBlogFromPdfApiV1BlogPdfPostResponses]

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostData = {
  body: BodyGenerateBlogFromPdfStreamApiV1BlogPdfStreamPost
  path?: never
  query?: never
  url: '/api/v1/blog/pdf/stream'
}

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostError =
  GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors[keyof GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors]

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ChatWithPaperApiV1ChatPaperPaperIdPostData = {
  body: ChatRequest
  path: {
    /**
     * Paper Id
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/chat/paper/{paper_id}'
}

export type ChatWithPaperApiV1ChatPaperPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ChatWithPaperApiV1ChatPaperPaperIdPostError =
  ChatWithPaperApiV1ChatPaperPaperIdPostErrors[keyof ChatWithPaperApiV1ChatPaperPaperIdPostErrors]

export type ChatWithPaperApiV1ChatPaperPaperIdPostResponses = {
  /**
   * SSE stream of ChatStreamEvent objects
   */
  200: unknown
}

export type ListChatThreadsApiV1ChatPaperPaperIdThreadsGetData = {
  body?: never
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/chat/paper/{paper_id}/threads'
}

export type ListChatThreadsApiV1ChatPaperPaperIdThreadsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListChatThreadsApiV1ChatPaperPaperIdThreadsGetError =
  ListChatThreadsApiV1ChatPaperPaperIdThreadsGetErrors[keyof ListChatThreadsApiV1ChatPaperPaperIdThreadsGetErrors]

export type ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponses = {
  /**
   * Successful Response
   */
  200: ChatThreadListResponse
}

export type ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponse =
  ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponses[keyof ListChatThreadsApiV1ChatPaperPaperIdThreadsGetResponses]

export type DeleteChatThreadApiV1ChatThreadsThreadIdDeleteData = {
  body?: never
  path: {
    /**
     * Thread Id
     *
     * The thread ID
     */
    thread_id: string
  }
  query?: never
  url: '/api/v1/chat/threads/{thread_id}'
}

export type DeleteChatThreadApiV1ChatThreadsThreadIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type DeleteChatThreadApiV1ChatThreadsThreadIdDeleteError =
  DeleteChatThreadApiV1ChatThreadsThreadIdDeleteErrors[keyof DeleteChatThreadApiV1ChatThreadsThreadIdDeleteErrors]

export type DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponse =
  DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponses[keyof DeleteChatThreadApiV1ChatThreadsThreadIdDeleteResponses]

export type GetChatThreadApiV1ChatThreadsThreadIdGetData = {
  body?: never
  path: {
    /**
     * Thread Id
     *
     * The thread ID
     */
    thread_id: string
  }
  query?: never
  url: '/api/v1/chat/threads/{thread_id}'
}

export type GetChatThreadApiV1ChatThreadsThreadIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetChatThreadApiV1ChatThreadsThreadIdGetError =
  GetChatThreadApiV1ChatThreadsThreadIdGetErrors[keyof GetChatThreadApiV1ChatThreadsThreadIdGetErrors]

export type GetChatThreadApiV1ChatThreadsThreadIdGetResponses = {
  /**
   * Successful Response
   */
  200: ChatThreadResponse
}

export type GetChatThreadApiV1ChatThreadsThreadIdGetResponse =
  GetChatThreadApiV1ChatThreadsThreadIdGetResponses[keyof GetChatThreadApiV1ChatThreadsThreadIdGetResponses]

export type GetMyChatDailyCountApiV1ChatMyDailyCountGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/chat/my/daily-count'
}

export type GetMyChatDailyCountApiV1ChatMyDailyCountGetResponses = {
  /**
   * Successful Response
   */
  200: ChatDailyCountResponse
}

export type GetMyChatDailyCountApiV1ChatMyDailyCountGetResponse =
  GetMyChatDailyCountApiV1ChatMyDailyCountGetResponses[keyof GetMyChatDailyCountApiV1ChatMyDailyCountGetResponses]

export type GetMySubscriptionApiV1BillingMeGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/billing/me'
}

export type GetMySubscriptionApiV1BillingMeGetResponses = {
  /**
   * Successful Response
   */
  200: MySubscriptionResponse
}

export type GetMySubscriptionApiV1BillingMeGetResponse =
  GetMySubscriptionApiV1BillingMeGetResponses[keyof GetMySubscriptionApiV1BillingMeGetResponses]

export type CreateCheckoutSessionApiV1BillingCheckoutSessionPostData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/billing/checkout-session'
}

export type CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponses = {
  /**
   * Successful Response
   */
  200: RedirectUrlResponse
}

export type CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponse =
  CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponses[keyof CreateCheckoutSessionApiV1BillingCheckoutSessionPostResponses]

export type CreatePortalSessionApiV1BillingPortalSessionPostData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/billing/portal-session'
}

export type CreatePortalSessionApiV1BillingPortalSessionPostResponses = {
  /**
   * Successful Response
   */
  200: RedirectUrlResponse
}

export type CreatePortalSessionApiV1BillingPortalSessionPostResponse =
  CreatePortalSessionApiV1BillingPortalSessionPostResponses[keyof CreatePortalSessionApiV1BillingPortalSessionPostResponses]

export type StripeWebhookApiV1BillingWebhookPostData = {
  body?: never
  headers?: {
    /**
     * Stripe-Signature
     */
    'stripe-signature'?: string | null
  }
  path?: never
  query?: never
  url: '/api/v1/billing/webhook'
}

export type StripeWebhookApiV1BillingWebhookPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type StripeWebhookApiV1BillingWebhookPostError =
  StripeWebhookApiV1BillingWebhookPostErrors[keyof StripeWebhookApiV1BillingWebhookPostErrors]

export type StripeWebhookApiV1BillingWebhookPostResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type StripeWebhookApiV1BillingWebhookPostResponse =
  StripeWebhookApiV1BillingWebhookPostResponses[keyof StripeWebhookApiV1BillingWebhookPostResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type TriggerErrorSentryDebugGetData = {
  body?: never
  path?: never
  query?: never
  url: '/sentry-debug'
}

export type TriggerErrorSentryDebugGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
