// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * BlogPostResponseSchema
 */
export type BlogPostResponseSchema = {
  /**
   * Paper Id
   */
  paper_id: string
  /**
   * Title
   */
  title: string
  /**
   * Summary
   */
  summary: string
  /**
   * Authors
   */
  authors: Array<string>
  /**
   * Source Url
   */
  source_url: string | null
  /**
   * Content
   */
  content: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * Body_generate_blog_from_pdf_api_v1_blog_pdf_post
 */
export type BodyGenerateBlogFromPdfApiV1BlogPdfPost = {
  /**
   * File
   *
   * PDF file of the paper
   */
  file: Blob | File
}

/**
 * Body_generate_blog_from_pdf_stream_api_v1_blog_pdf_stream_post
 */
export type BodyGenerateBlogFromPdfStreamApiV1BlogPdfStreamPost = {
  /**
   * File
   *
   * PDF file of the paper
   */
  file: Blob | File
}

/**
 * GenerationCountResponseSchema
 */
export type GenerationCountResponseSchema = {
  /**
   * Monthly
   */
  monthly: number
  /**
   * Total
   */
  total: number
  /**
   * Limit
   */
  limit: number
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * PaginatedBlogPostResponseSchema
 */
export type PaginatedBlogPostResponseSchema = {
  /**
   * Items
   */
  items: Array<BlogPostResponseSchema>
  /**
   * Total
   */
  total: number
  /**
   * Page
   */
  page: number
  /**
   * Page Size
   */
  page_size: number
  /**
   * Total Pages
   */
  total_pages: number
}

/**
 * RagImageItemSchema
 */
export type RagImageItemSchema = {
  /**
   * Image Url
   */
  image_url: string
  /**
   * Caption
   */
  caption: string | null
  /**
   * Page Number
   */
  page_number: number
}

/**
 * RagSearchImageResponseSchema
 */
export type RagSearchImageResponseSchema = {
  /**
   * Items
   */
  items: Array<RagImageItemSchema>
}

/**
 * RagSearchRequestSchema
 */
export type RagSearchRequestSchema = {
  /**
   * Query
   */
  query: string
  /**
   * Limit
   */
  limit?: number
}

/**
 * RagSearchTextResponseSchema
 */
export type RagSearchTextResponseSchema = {
  /**
   * Chunks
   */
  chunks: Array<RagTextChunkSchema>
}

/**
 * RagTextChunkSchema
 */
export type RagTextChunkSchema = {
  /**
   * Text
   */
  text: string
  /**
   * Page Number
   */
  page_number: number
}

/**
 * TargetLanguage
 *
 * The target language for translation.
 */
export type TargetLanguage = 'japanese'

/**
 * TranslateResponseSchema
 */
export type TranslateResponseSchema = {
  /**
   * Message
   */
  message: string
  /**
   * Translated Pdf Url
   */
  translated_pdf_url: string
  /**
   * Translated Language
   */
  translated_language: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The ID of the paper
     */
    arxiv_paper_id: string
  }
  query: {
    /**
     * The target language
     */
    target_language: TargetLanguage
  }
  url: '/api/v1/translate/arxiv/{arxiv_paper_id}'
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostError =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors]

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: TranslateResponseSchema
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponse =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses]

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The ID of the paper
     */
    arxiv_paper_id: string
  }
  query: {
    /**
     * The target language
     */
    target_language: TargetLanguage
  }
  url: '/api/v1/translate/arxiv/{arxiv_paper_id}/stream'
}

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetError =
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors[keyof TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors]

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ListBlogsApiV1BlogGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number
  }
  url: '/api/v1/blog/'
}

export type ListBlogsApiV1BlogGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListBlogsApiV1BlogGetError =
  ListBlogsApiV1BlogGetErrors[keyof ListBlogsApiV1BlogGetErrors]

export type ListBlogsApiV1BlogGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedBlogPostResponseSchema
}

export type ListBlogsApiV1BlogGetResponse =
  ListBlogsApiV1BlogGetResponses[keyof ListBlogsApiV1BlogGetResponses]

export type ListMyBlogsApiV1BlogMyGetData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number
  }
  url: '/api/v1/blog/my'
}

export type ListMyBlogsApiV1BlogMyGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ListMyBlogsApiV1BlogMyGetError =
  ListMyBlogsApiV1BlogMyGetErrors[keyof ListMyBlogsApiV1BlogMyGetErrors]

export type ListMyBlogsApiV1BlogMyGetResponses = {
  /**
   * Successful Response
   */
  200: PaginatedBlogPostResponseSchema
}

export type ListMyBlogsApiV1BlogMyGetResponse =
  ListMyBlogsApiV1BlogMyGetResponses[keyof ListMyBlogsApiV1BlogMyGetResponses]

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/blog/my/generation-count'
}

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses = {
  /**
   * Successful Response
   */
  200: GenerationCountResponseSchema
}

export type GetMyGenerationCountApiV1BlogMyGenerationCountGetResponse =
  GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses[keyof GetMyGenerationCountApiV1BlogMyGenerationCountGetResponses]

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The arXiv paper ID
     */
    arxiv_paper_id: string
  }
  query?: never
  url: '/api/v1/blog/arxiv/{arxiv_paper_id}'
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostError =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors]

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponse =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses]

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The arXiv paper ID
     */
    arxiv_paper_id: string
  }
  query?: never
  url: '/api/v1/blog/arxiv/{arxiv_paper_id}/stream'
}

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetError =
  GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors[keyof GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetErrors]

export type GenerateBlogStreamApiV1BlogArxivArxivPaperIdStreamGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostData = {
  body: RagSearchRequestSchema
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}/rag/text'
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostError =
  RagSearchTextApiV1BlogPaperIdRagTextPostErrors[keyof RagSearchTextApiV1BlogPaperIdRagTextPostErrors]

export type RagSearchTextApiV1BlogPaperIdRagTextPostResponses = {
  /**
   * Successful Response
   */
  200: RagSearchTextResponseSchema
}

export type RagSearchTextApiV1BlogPaperIdRagTextPostResponse =
  RagSearchTextApiV1BlogPaperIdRagTextPostResponses[keyof RagSearchTextApiV1BlogPaperIdRagTextPostResponses]

export type RagSearchImageApiV1BlogPaperIdRagImagePostData = {
  body: RagSearchRequestSchema
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}/rag/image'
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostError =
  RagSearchImageApiV1BlogPaperIdRagImagePostErrors[keyof RagSearchImageApiV1BlogPaperIdRagImagePostErrors]

export type RagSearchImageApiV1BlogPaperIdRagImagePostResponses = {
  /**
   * Successful Response
   */
  200: RagSearchImageResponseSchema
}

export type RagSearchImageApiV1BlogPaperIdRagImagePostResponse =
  RagSearchImageApiV1BlogPaperIdRagImagePostResponses[keyof RagSearchImageApiV1BlogPaperIdRagImagePostResponses]

export type GetBlogApiV1BlogPaperIdGetData = {
  body?: never
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}'
}

export type GetBlogApiV1BlogPaperIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetBlogApiV1BlogPaperIdGetError =
  GetBlogApiV1BlogPaperIdGetErrors[keyof GetBlogApiV1BlogPaperIdGetErrors]

export type GetBlogApiV1BlogPaperIdGetResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GetBlogApiV1BlogPaperIdGetResponse =
  GetBlogApiV1BlogPaperIdGetResponses[keyof GetBlogApiV1BlogPaperIdGetResponses]

export type GenerateBlogFromPdfApiV1BlogPdfPostData = {
  body: BodyGenerateBlogFromPdfApiV1BlogPdfPost
  path?: never
  query?: never
  url: '/api/v1/blog/pdf'
}

export type GenerateBlogFromPdfApiV1BlogPdfPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogFromPdfApiV1BlogPdfPostError =
  GenerateBlogFromPdfApiV1BlogPdfPostErrors[keyof GenerateBlogFromPdfApiV1BlogPdfPostErrors]

export type GenerateBlogFromPdfApiV1BlogPdfPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogFromPdfApiV1BlogPdfPostResponse =
  GenerateBlogFromPdfApiV1BlogPdfPostResponses[keyof GenerateBlogFromPdfApiV1BlogPdfPostResponses]

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostData = {
  body: BodyGenerateBlogFromPdfStreamApiV1BlogPdfStreamPost
  path?: never
  query?: never
  url: '/api/v1/blog/pdf/stream'
}

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostError =
  GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors[keyof GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostErrors]

export type GenerateBlogFromPdfStreamApiV1BlogPdfStreamPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type TriggerErrorSentryDebugGetData = {
  body?: never
  path?: never
  query?: never
  url: '/sentry-debug'
}

export type TriggerErrorSentryDebugGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
