// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * BlogPostResponseSchema
 */
export type BlogPostResponseSchema = {
  /**
   * Paper Id
   */
  paper_id: string
  /**
   * Title
   */
  title: string
  /**
   * Summary
   */
  summary: string
  /**
   * Authors
   */
  authors: Array<string>
  /**
   * Source Url
   */
  source_url: string | null
  /**
   * Content
   */
  content: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * Body_generate_blog_from_pdf_api_v1_blog_pdf_post
 */
export type BodyGenerateBlogFromPdfApiV1BlogPdfPost = {
  /**
   * File
   *
   * PDF file of the paper
   */
  file: Blob | File
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * TargetLanguage
 *
 * The target language for translation.
 */
export type TargetLanguage = 'japanese'

/**
 * TranslateResponseSchema
 */
export type TranslateResponseSchema = {
  /**
   * Message
   */
  message: string
  /**
   * Translated Pdf Url
   */
  translated_pdf_url: string
  /**
   * Translated Language
   */
  translated_language: string
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type ListBlogsApiV1BlogGetData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/blog/'
}

export type ListBlogsApiV1BlogGetResponses = {
  /**
   * Response List Blogs Api V1 Blog  Get
   *
   * Successful Response
   */
  200: Array<BlogPostResponseSchema>
}

export type ListBlogsApiV1BlogGetResponse =
  ListBlogsApiV1BlogGetResponses[keyof ListBlogsApiV1BlogGetResponses]

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The ID of the paper
     */
    arxiv_paper_id: string
  }
  query: {
    /**
     * The target language
     */
    target_language: TargetLanguage
  }
  url: '/api/v1/translate/arxiv/{arxiv_paper_id}'
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostError =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostErrors]

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: TranslateResponseSchema
}

export type TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponse =
  TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses[keyof TranslateSyncApiV1TranslateArxivArxivPaperIdPostResponses]

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The ID of the paper
     */
    arxiv_paper_id: string
  }
  query: {
    /**
     * The target language
     */
    target_language: TargetLanguage
  }
  url: '/api/v1/translate/arxiv/{arxiv_paper_id}/stream'
}

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetError =
  TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors[keyof TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetErrors]

export type TranslateStreamApiV1TranslateArxivArxivPaperIdStreamGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostData = {
  body?: never
  path: {
    /**
     * Arxiv Paper Id
     *
     * The arXiv paper ID
     */
    arxiv_paper_id: string
  }
  query?: never
  url: '/api/v1/blog/arxiv/{arxiv_paper_id}'
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostError =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostErrors]

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogApiV1BlogArxivArxivPaperIdPostResponse =
  GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses[keyof GenerateBlogApiV1BlogArxivArxivPaperIdPostResponses]

export type GetBlogApiV1BlogPaperIdGetData = {
  body?: never
  path: {
    /**
     * Paper Id
     *
     * The paper ID
     */
    paper_id: string
  }
  query?: never
  url: '/api/v1/blog/{paper_id}'
}

export type GetBlogApiV1BlogPaperIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetBlogApiV1BlogPaperIdGetError =
  GetBlogApiV1BlogPaperIdGetErrors[keyof GetBlogApiV1BlogPaperIdGetErrors]

export type GetBlogApiV1BlogPaperIdGetResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GetBlogApiV1BlogPaperIdGetResponse =
  GetBlogApiV1BlogPaperIdGetResponses[keyof GetBlogApiV1BlogPaperIdGetResponses]

export type GenerateBlogFromPdfApiV1BlogPdfPostData = {
  body: BodyGenerateBlogFromPdfApiV1BlogPdfPost
  path?: never
  query?: never
  url: '/api/v1/blog/pdf'
}

export type GenerateBlogFromPdfApiV1BlogPdfPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GenerateBlogFromPdfApiV1BlogPdfPostError =
  GenerateBlogFromPdfApiV1BlogPdfPostErrors[keyof GenerateBlogFromPdfApiV1BlogPdfPostErrors]

export type GenerateBlogFromPdfApiV1BlogPdfPostResponses = {
  /**
   * Successful Response
   */
  200: BlogPostResponseSchema
}

export type GenerateBlogFromPdfApiV1BlogPdfPostResponse =
  GenerateBlogFromPdfApiV1BlogPdfPostResponses[keyof GenerateBlogFromPdfApiV1BlogPdfPostResponses]

export type RootGetData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type TriggerErrorSentryDebugGetData = {
  body?: never
  path?: never
  query?: never
  url: '/sentry-debug'
}

export type TriggerErrorSentryDebugGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}
